### ISSUE TITLE
Attribute error Mesh object has no attribute 'vertex_layer_float'

### ISSUE THREAD

**Issue by AronWick** [SilentNightSound/SR-Model-Importer#39]
I can't export a HSR model (tried Sparkle and Fu Xuan) not edited, getting

```
Python: Traceback (most recent call last):
  File "C:\Users\Aron\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_3dmigoto_srmi.py", line 2555, in execute
    export_3dmigoto_genshin(self, context, object_name, vb_path, ib_path, fmt_path, self.use_foldername,
  File "C:\Users\Aron\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_3dmigoto_srmi.py", line 1663, in export_3dmigoto_genshin
    vertex = blender_vertex_to_3dmigoto_vertex(mesh, obj, blender_lvertex, layout, texcoord_layers)
  File "C:\Users\Aron\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_3dmigoto_srmi.py", line 1036, in blender_vertex_to_3dmigoto_vertex
    if 'POSITION.w' in mesh.vertex_layers_float:
AttributeError: 'Mesh' object has no attribute 'vertex_layers_float'
```

**Comment by SilentNightSound** [comment]
Hello! The plugin currently only supports up to Blender 3.6. There is an experimental one in AGMG discord you can use if you want to try Blender 4.0, but otherwise I would recommend staying on 3.6 for the near future until all the issues are handled
