### ISSUE TITLE
[Fatal] [Library Error] [Windows 11] Python: pyinjector.InjectorError | pyinjector 库报错

### ISSUE THREAD

**Issue by SuperScript-PRC** [SilentNightSound/SR-Model-Importer#44]
The 3dmigoto_loader.exe crashed an error. This is the discription:
3dmigoto_loader.exe 运行报错，命令行有权限。
> pyinjector.pyinjector.InjectorError: injector_inject returned -5: LoadLibrary in the target process failed: win32 error code 0xffffffff
```
Waiting for program...
Found
StarRail.exe 1724
Traceback (most recent call last):
  File "inject_3dm_HSR.py", line 19, in <module>
  File "inject_3dm_HSR.py", line 13, in main
  File "pyinjector\pyinjector.py", line 103, in inject
  File "pyinjector\pyinjector.py", line 87, in inject
  File "pyinjector\pyinjector.py", line 66, in call_c_func
pyinjector.pyinjector.InjectorError: injector_inject returned -5: LoadLibrary in the target process failed: win32 error code 0xffffffff
[16012] Failed to execute script 'inject_3dm_HSR' due to unhandled exception!
```
and so as Python source code (i have a Python 3.11 env)
运行Python源码仍然报错（环境是Python 3.11）
 - ImageFile:
![image](https://github.com/SilentNightSound/SR-Model-Importer/assets/112140997/7ac5fe43-f144-405a-bddb-0a623dc91aa7)

**Comment by mimmox** [comment]
Same

**Comment by shizuyounv** [comment]
以前重开一遍就好了，就这几天不管用了

**Comment by mimmox** [comment]
我的问题解决了，跟第三方软件有冲突，我的是输入法有冲突【搜狗输入法】。此外杀毒软件也会干扰 添加信任就可以了。
